// flow-typed signature: 9d4a553cde5fb4c36d3fc4dd78d200e1
// flow-typed version: <<STUB>>/react-photo-gallery_v5.6.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-photo-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-photo-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-photo-gallery/dist/react-photo-gallery' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/dist/react-photo-gallery.min' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/dist/app' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/dist/common' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/dist/standalone' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/examples/src/app' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/gulpfile' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/lib/Gallery' {
  declare module.exports: any;
}

declare module 'react-photo-gallery/src/Gallery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-photo-gallery/dist/react-photo-gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery'>;
}
declare module 'react-photo-gallery/dist/react-photo-gallery.min.js' {
  declare module.exports: $Exports<'react-photo-gallery/dist/react-photo-gallery.min'>;
}
declare module 'react-photo-gallery/examples/dist/app.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/dist/app'>;
}
declare module 'react-photo-gallery/examples/dist/bundle.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/dist/bundle'>;
}
declare module 'react-photo-gallery/examples/dist/common.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/dist/common'>;
}
declare module 'react-photo-gallery/examples/dist/standalone.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/dist/standalone'>;
}
declare module 'react-photo-gallery/examples/src/app.js' {
  declare module.exports: $Exports<'react-photo-gallery/examples/src/app'>;
}
declare module 'react-photo-gallery/gulpfile.js' {
  declare module.exports: $Exports<'react-photo-gallery/gulpfile'>;
}
declare module 'react-photo-gallery/lib/Gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/lib/Gallery'>;
}
declare module 'react-photo-gallery/src/Gallery.js' {
  declare module.exports: $Exports<'react-photo-gallery/src/Gallery'>;
}
