// flow-typed signature: 40b456e8d4f0ad73812560eb90f9fe75
// flow-typed version: <<STUB>>/rebass_v1.0.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebass/dist/blacklist' {
  declare module.exports: any;
}

declare module 'rebass/dist/clean-props' {
  declare module.exports: any;
}

declare module 'rebass/dist/components' {
  declare module.exports: any;
}

declare module 'rebass/dist/create-component' {
  declare module.exports: any;
}

declare module 'rebass/dist/create-library' {
  declare module.exports: any;
}

declare module 'rebass/dist/DonutBase' {
  declare module.exports: any;
}

declare module 'rebass/dist/grid' {
  declare module.exports: any;
}

declare module 'rebass/dist/hoc' {
  declare module.exports: any;
}

declare module 'rebass/dist/index' {
  declare module.exports: any;
}

declare module 'rebass/dist/Provider' {
  declare module.exports: any;
}

declare module 'rebass/dist/SelectBase' {
  declare module.exports: any;
}

declare module 'rebass/dist/style-props' {
  declare module.exports: any;
}

declare module 'rebass/dist/tag' {
  declare module.exports: any;
}

declare module 'rebass/dist/theme' {
  declare module.exports: any;
}

declare module 'rebass/dist/util' {
  declare module.exports: any;
}

declare module 'rebass/src/blacklist' {
  declare module.exports: any;
}

declare module 'rebass/src/components' {
  declare module.exports: any;
}

declare module 'rebass/src/create-component' {
  declare module.exports: any;
}

declare module 'rebass/src/create-library' {
  declare module.exports: any;
}

declare module 'rebass/src/DonutBase' {
  declare module.exports: any;
}

declare module 'rebass/src/grid' {
  declare module.exports: any;
}

declare module 'rebass/src/hoc' {
  declare module.exports: any;
}

declare module 'rebass/src/index' {
  declare module.exports: any;
}

declare module 'rebass/src/Provider' {
  declare module.exports: any;
}

declare module 'rebass/src/SelectBase' {
  declare module.exports: any;
}

declare module 'rebass/src/theme' {
  declare module.exports: any;
}

declare module 'rebass/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebass/dist/blacklist.js' {
  declare module.exports: $Exports<'rebass/dist/blacklist'>;
}
declare module 'rebass/dist/clean-props.js' {
  declare module.exports: $Exports<'rebass/dist/clean-props'>;
}
declare module 'rebass/dist/components.js' {
  declare module.exports: $Exports<'rebass/dist/components'>;
}
declare module 'rebass/dist/create-component.js' {
  declare module.exports: $Exports<'rebass/dist/create-component'>;
}
declare module 'rebass/dist/create-library.js' {
  declare module.exports: $Exports<'rebass/dist/create-library'>;
}
declare module 'rebass/dist/DonutBase.js' {
  declare module.exports: $Exports<'rebass/dist/DonutBase'>;
}
declare module 'rebass/dist/grid.js' {
  declare module.exports: $Exports<'rebass/dist/grid'>;
}
declare module 'rebass/dist/hoc.js' {
  declare module.exports: $Exports<'rebass/dist/hoc'>;
}
declare module 'rebass/dist/index.js' {
  declare module.exports: $Exports<'rebass/dist/index'>;
}
declare module 'rebass/dist/Provider.js' {
  declare module.exports: $Exports<'rebass/dist/Provider'>;
}
declare module 'rebass/dist/SelectBase.js' {
  declare module.exports: $Exports<'rebass/dist/SelectBase'>;
}
declare module 'rebass/dist/style-props.js' {
  declare module.exports: $Exports<'rebass/dist/style-props'>;
}
declare module 'rebass/dist/tag.js' {
  declare module.exports: $Exports<'rebass/dist/tag'>;
}
declare module 'rebass/dist/theme.js' {
  declare module.exports: $Exports<'rebass/dist/theme'>;
}
declare module 'rebass/dist/util.js' {
  declare module.exports: $Exports<'rebass/dist/util'>;
}
declare module 'rebass/src/blacklist.js' {
  declare module.exports: $Exports<'rebass/src/blacklist'>;
}
declare module 'rebass/src/components.js' {
  declare module.exports: $Exports<'rebass/src/components'>;
}
declare module 'rebass/src/create-component.js' {
  declare module.exports: $Exports<'rebass/src/create-component'>;
}
declare module 'rebass/src/create-library.js' {
  declare module.exports: $Exports<'rebass/src/create-library'>;
}
declare module 'rebass/src/DonutBase.js' {
  declare module.exports: $Exports<'rebass/src/DonutBase'>;
}
declare module 'rebass/src/grid.js' {
  declare module.exports: $Exports<'rebass/src/grid'>;
}
declare module 'rebass/src/hoc.js' {
  declare module.exports: $Exports<'rebass/src/hoc'>;
}
declare module 'rebass/src/index.js' {
  declare module.exports: $Exports<'rebass/src/index'>;
}
declare module 'rebass/src/Provider.js' {
  declare module.exports: $Exports<'rebass/src/Provider'>;
}
declare module 'rebass/src/SelectBase.js' {
  declare module.exports: $Exports<'rebass/src/SelectBase'>;
}
declare module 'rebass/src/theme.js' {
  declare module.exports: $Exports<'rebass/src/theme'>;
}
declare module 'rebass/src/util.js' {
  declare module.exports: $Exports<'rebass/src/util'>;
}
